name: uber_shop
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4

  firebase_auth: ^4.7.2
  image_picker: ^1.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.4.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.4.0
  flutter_stripe: ^9.4.0
  http: ^1.1.0



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  uuid: ^4.1.0
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/welcome.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/market.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

