name: uber_shop
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4

  firebase_auth: ^4.7.2
  image_picker: ^1.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.5.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.4.0



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

